apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: yc4x2hcxy-nodejs
  janus-idp.io/tekton: yc4x2hcxy-nodejs
  backstage.io/kubernetes-id: yc4x2hcxy-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: yc4x2hcxy-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
