apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: yc4x2hcxy-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: yc4x2hcxy-nodejs 
  name: yc4x2hcxy-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: yc4x2hcxy-nodejs 
